version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run: ./gradlew check jacocoRootReport
      - store_artifacts:
          path: ./build/reports
