version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u252

    steps:
      - run:
          command: ./gradlew clean test

      - run:
          command: ./gradlew check jacocoRootReport
